from sqlalchemy.orm import Session
from typing import List, Set
from database.tables.users import User
from database.tables.deals import Deal
from database.tables.accounts import Account
from services.business_rules import DEAL_STAGE_LOST, DEAL_STAGE_WON

class DealAccessService:
    def __init__(self, db: Session):
        self.db = db
    
    def get_subordinates_recursive(self, manager_ecode: str, visited: Set[str] = None) -> List[str]:
        """
        Get all subordinates using depth-first search
        """
        if visited is None:
            visited = set()
        
        # Prevent infinite loops
        if manager_ecode in visited:
            return []
        
        visited.add(manager_ecode)
        subordinates = []
        
        # Find direct subordinates
        direct_subordinates = self.db.query(User).filter(
            User.ReportingManagerECode == manager_ecode
        ).all()
        
        for subordinate in direct_subordinates:
            subordinates.append(subordinate.ECode)
            # Recursively get subordinates of subordinates
            sub_subordinates = self.get_subordinates_recursive(subordinate.ECode, visited.copy())
            subordinates.extend(sub_subordinates)
        
        return subordinates
    
    def is_user_kam_for_deal(self, user_ecode: str, deal: Deal) -> bool:
        """
        Check if user is the appropriate KAM for this deal
        """
        # Use the stored KAM from the deal instead of computing it from account
        return deal.KAMECode == user_ecode
    
    def is_deal_draggable(self, deal: Deal, user_ecode: str, is_subordinate_deal: bool = False) -> bool:
        """
        Determine if a deal should be draggable based on business rules
        """
        # All subordinate deals are not draggable
        if is_subordinate_deal:
            return False
        
        # Deals with certain statuses are not draggable
        # Note: PENDING deals are not draggable (waiting for approval)
        # REJECTED deals are not draggable
        # APPROVED deals can be draggable if user has proper access
        non_draggable_statuses = ["PENDING", "REJECTED"]
        if deal.Status.value in non_draggable_statuses:
            return False
        
        # Deals in certain stages are not draggable
        non_draggable_stages = [DEAL_STAGE_WON, DEAL_STAGE_LOST]
        if deal.Stage in non_draggable_stages:
            return False
        
        # User must be salesperson or KAM to drag
        is_salesperson = deal.SalespersonECode == user_ecode
        is_kam = self.is_user_kam_for_deal(user_ecode, deal)
        
        return is_salesperson or is_kam

    def get_authorized_deals(self, user_ecode: str, user_role: str = None) -> List[dict]:
        """
        Get all deals the user is authorized to view based on role and access rights
        
        Role-based access:
        - MD Office: Can view all deals
        - Lead Generator: Can view deals they generated + standard access
        - Other roles: Standard access (salesperson, KAM, subordinate deals)
        """
        # Get user role if not provided
        if user_role is None:
            user = self.db.query(User).filter(User.ECode == user_ecode).first()
            user_role = user.Role if user else None
        
        # MD Office role: Access to all deals
        if user_role == 'MD Office' or user_role == 'Finance':
            return self._get_all_deals_for_md_office()
        
        # Lead Generator role: Access to generated deals + standard access
        if user_role == 'Lead Generator':
            return self._get_deals_for_lead_generator(user_ecode)
        
        # Standard access for other roles
        return self._get_standard_authorized_deals(user_ecode)
    
    def _get_all_deals_for_md_office(self) -> List[dict]:
        """
        Get all deals for MD Office role
        """
        all_deals = self.db.query(Deal).all()
        return [{
            'deal': deal,
            'is_subordinate': False,
            'access_type': 'md_office'
        } for deal in all_deals]
    
    def _get_deals_for_lead_generator(self, user_ecode: str) -> List[dict]:
        """
        Get deals for Lead Generator role (generated deals + standard access)
        """
        user_deals = []
        existing_deal_ids = set()
        
        # 1. Get deals generated by this user
        generated_deals = self.db.query(Deal).filter(
            Deal.LeadGeneratedBy == user_ecode
        ).all()
        
        for deal in generated_deals:
            user_deals.append({
                'deal': deal,
                'is_subordinate': False,
                'access_type': 'lead_generator'
            })
            existing_deal_ids.add(deal.ID)
        
        # 2. Add standard access deals (avoiding duplicates)
        standard_deals = self._get_standard_authorized_deals(user_ecode)
        for deal_info in standard_deals:
            if deal_info['deal'].ID not in existing_deal_ids:
                user_deals.append(deal_info)
        
        return user_deals
    
    def _get_standard_authorized_deals(self, user_ecode: str) -> List[dict]:
        """
        Get standard authorized deals (salesperson, KAM, subordinate access)
        """
        user_deals = []
        existing_deal_ids = set()
        
        # 1. Get deals where user is salesperson
        salesperson_deals = self.db.query(Deal).filter(
            Deal.SalespersonECode == user_ecode
        ).all()
        
        for deal in salesperson_deals:
            user_deals.append({
                'deal': deal,
                'is_subordinate': False,
                'access_type': 'salesperson'
            })
            existing_deal_ids.add(deal.ID)
        
        # 2. Get deals where user is KAM
        kam_deals = self.db.query(Deal).filter(
            Deal.KAMECode == user_ecode
        ).all()
        
        # Add KAM deals that aren't already included
        for deal in kam_deals:
            if deal.ID not in existing_deal_ids:
                user_deals.append({
                    'deal': deal,
                    'is_subordinate': False,
                    'access_type': 'kam'
                })
                existing_deal_ids.add(deal.ID)
        
        # 3. Get deals from subordinates
        subordinates = self.get_subordinates_recursive(user_ecode)
        if subordinates:
            subordinate_deals = self.db.query(Deal).filter(
                Deal.SalespersonECode.in_(subordinates)
            ).all()
            
            for deal in subordinate_deals:
                if deal.ID not in existing_deal_ids:
                    user_deals.append({
                        'deal': deal,
                        'is_subordinate': True,
                        'access_type': 'subordinate'
                    })
        
        return user_deals
    
    def has_deal_access(self, user_ecode: str, deal_id: int, user_role: str = None) -> bool:
        """
        Check if user has access to a specific deal
        Utility method for single deal access validation
        """
        authorized_deals = self.get_authorized_deals(user_ecode, user_role)
        authorized_deal_ids = {deal_info['deal'].ID for deal_info in authorized_deals}
        return deal_id in authorized_deal_ids
